-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.Object exposing (Film(..), FilmCharactersConnection(..), FilmCharactersEdge(..), FilmPlanetsConnection(..), FilmPlanetsEdge(..), FilmSpeciesConnection(..), FilmSpeciesEdge(..), FilmStarshipsConnection(..), FilmStarshipsEdge(..), FilmVehiclesConnection(..), FilmVehiclesEdge(..), FilmsConnection(..), FilmsEdge(..), PageInfo(..), PeopleConnection(..), PeopleEdge(..), Person(..), PersonFilmsConnection(..), PersonFilmsEdge(..), PersonStarshipsConnection(..), PersonStarshipsEdge(..), PersonVehiclesConnection(..), PersonVehiclesEdge(..), Planet(..), PlanetFilmsConnection(..), PlanetFilmsEdge(..), PlanetResidentsConnection(..), PlanetResidentsEdge(..), PlanetsConnection(..), PlanetsEdge(..), Species(..), SpeciesConnection(..), SpeciesEdge(..), SpeciesFilmsConnection(..), SpeciesFilmsEdge(..), SpeciesPeopleConnection(..), SpeciesPeopleEdge(..), Starship(..), StarshipFilmsConnection(..), StarshipFilmsEdge(..), StarshipPilotsConnection(..), StarshipPilotsEdge(..), StarshipsConnection(..), StarshipsEdge(..), Vehicle(..), VehicleFilmsConnection(..), VehicleFilmsEdge(..), VehiclePilotsConnection(..), VehiclePilotsEdge(..), VehiclesConnection(..), VehiclesEdge(..))


type Film
    = Film


type FilmCharactersConnection
    = FilmCharactersConnection


type FilmCharactersEdge
    = FilmCharactersEdge


type FilmPlanetsConnection
    = FilmPlanetsConnection


type FilmPlanetsEdge
    = FilmPlanetsEdge


type FilmSpeciesConnection
    = FilmSpeciesConnection


type FilmSpeciesEdge
    = FilmSpeciesEdge


type FilmStarshipsConnection
    = FilmStarshipsConnection


type FilmStarshipsEdge
    = FilmStarshipsEdge


type FilmVehiclesConnection
    = FilmVehiclesConnection


type FilmVehiclesEdge
    = FilmVehiclesEdge


type FilmsConnection
    = FilmsConnection


type FilmsEdge
    = FilmsEdge


type PageInfo
    = PageInfo


type PeopleConnection
    = PeopleConnection


type PeopleEdge
    = PeopleEdge


type Person
    = Person


type PersonFilmsConnection
    = PersonFilmsConnection


type PersonFilmsEdge
    = PersonFilmsEdge


type PersonStarshipsConnection
    = PersonStarshipsConnection


type PersonStarshipsEdge
    = PersonStarshipsEdge


type PersonVehiclesConnection
    = PersonVehiclesConnection


type PersonVehiclesEdge
    = PersonVehiclesEdge


type Planet
    = Planet


type PlanetFilmsConnection
    = PlanetFilmsConnection


type PlanetFilmsEdge
    = PlanetFilmsEdge


type PlanetResidentsConnection
    = PlanetResidentsConnection


type PlanetResidentsEdge
    = PlanetResidentsEdge


type PlanetsConnection
    = PlanetsConnection


type PlanetsEdge
    = PlanetsEdge


type Species
    = Species


type SpeciesConnection
    = SpeciesConnection


type SpeciesEdge
    = SpeciesEdge


type SpeciesFilmsConnection
    = SpeciesFilmsConnection


type SpeciesFilmsEdge
    = SpeciesFilmsEdge


type SpeciesPeopleConnection
    = SpeciesPeopleConnection


type SpeciesPeopleEdge
    = SpeciesPeopleEdge


type Starship
    = Starship


type StarshipFilmsConnection
    = StarshipFilmsConnection


type StarshipFilmsEdge
    = StarshipFilmsEdge


type StarshipPilotsConnection
    = StarshipPilotsConnection


type StarshipPilotsEdge
    = StarshipPilotsEdge


type StarshipsConnection
    = StarshipsConnection


type StarshipsEdge
    = StarshipsEdge


type Vehicle
    = Vehicle


type VehicleFilmsConnection
    = VehicleFilmsConnection


type VehicleFilmsEdge
    = VehicleFilmsEdge


type VehiclePilotsConnection
    = VehiclePilotsConnection


type VehiclePilotsEdge
    = VehiclePilotsEdge


type VehiclesConnection
    = VehiclesConnection


type VehiclesEdge
    = VehiclesEdge
