-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.ScalarCodecs exposing (Id, codecs)

import Json.Decode as Decode exposing (Decoder)
import StarWars.Scalar exposing (defaultCodecs)


type alias Id =
    StarWars.Scalar.Id


codecs : StarWars.Scalar.Codecs Id
codecs =
    StarWars.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
