-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.Object.StarshipPilotsConnection exposing (edges, pageInfo, pilots, totalCount)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import StarWars.InputObject
import StarWars.Interface
import StarWars.Object
import StarWars.Scalar
import StarWars.ScalarCodecs
import StarWars.Union


{-| Information to aid in pagination.
-}
pageInfo : SelectionSet decodesTo StarWars.Object.PageInfo -> SelectionSet decodesTo StarWars.Object.StarshipPilotsConnection
pageInfo object_ =
    Object.selectionForCompositeField "pageInfo" [] object_ identity


{-| A list of edges.
-}
edges : SelectionSet decodesTo StarWars.Object.StarshipPilotsEdge -> SelectionSet (Maybe (List (Maybe decodesTo))) StarWars.Object.StarshipPilotsConnection
edges object_ =
    Object.selectionForCompositeField "edges" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| A count of the total number of objects in this connection, ignoring pagination.
This allows a client to fetch the first five objects by passing "5" as the
argument to "first", then fetch the total count so it could display "5 of 83",
for example.
-}
totalCount : SelectionSet (Maybe Int) StarWars.Object.StarshipPilotsConnection
totalCount =
    Object.selectionForField "(Maybe Int)" "totalCount" [] (Decode.int |> Decode.nullable)


{-| A list of all of the objects returned in the connection. This is a convenience
field provided for quickly exploring the API; rather than querying for
"{ edges { node } }" when no edge data is needed, this field can be be used
instead. Note that when clients like Relay need to fetch the "cursor" field on
the edge to enable efficient pagination, this shortcut cannot be used, and the
full "{ edges { node } }" version should be used instead.
-}
pilots : SelectionSet decodesTo StarWars.Object.Person -> SelectionSet (Maybe (List (Maybe decodesTo))) StarWars.Object.StarshipPilotsConnection
pilots object_ =
    Object.selectionForCompositeField "pilots" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
